name: Deploy to Server

on:
  workflow_dispatch: # Allow manual triggering of the workflow from the GitHub Actions tab
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: fet
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The script value doesn't strictly matter if you use the
          # 'command' restriction in authorized_keys, but this is a good fallback.
          script: /home/fet/all-projects/faculty_mis/deploy.sh
